# Generated by Django 5.1.3 on 2024-11-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeastType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('degree', models.CharField(choices=[('mandatory', 'Mandatory'), ('optional', 'Optional'), ('recommended', 'Recommended')], max_length=50)),
                ('date', models.DateField()),
                ('types', models.ManyToManyField(related_name='feasts', to='feasts.feasttype')),
            ],
        ),
    ]
