# Generated by Django 5.1.3 on 2024-11-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feast',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
