# Generated by Django 5.1.3 on 2024-11-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasts', '0002_feast_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feast',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
