# Generated by Django 5.1.3 on 2024-11-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasts', '0004_remove_feast_date_remove_feast_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feast',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feasttype',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='liturgicalcalendar',
            name='season',
            field=models.CharField(max_length=500),
        ),
    ]
