# Generated by Django 5.1.3 on 2024-11-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasts', '0005_alter_feast_name_alter_feasttype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feast',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feast',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='feasttype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='liturgicalcalendar',
            name='season',
            field=models.CharField(max_length=100),
        ),
    ]
