# Generated by Django 5.1.3 on 2025-03-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celebration',
            options={'ordering': ['name']},
        ),
    ]
