# Generated by Django 5.1.3 on 2025-04-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrations', '0002_alter_celebration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebration',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='celebrationtype',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
