# Generated by Django 5.1.3 on 2025-04-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrations', '0003_celebration_description_alter_celebration_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebration',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='celebrations', to='celebrations.celebrationtype'),
        ),
    ]
