# Generated by Django 5.1.3 on 2024-11-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celebrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('liturgical_season', models.CharField(blank=True, max_length=50, null=True)),
                ('celebration', models.ManyToManyField(blank=True, related_name='songs', to='celebrations.celebration')),
                ('celebration_types', models.ManyToManyField(blank=True, related_name='songs', to='celebrations.celebrationtype')),
            ],
        ),
    ]
