# Generated by Django 5.1.3 on 2025-03-12 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrations', '0002_alter_celebration_options'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('songs', '0002_keyword_liturgicalseason_occasion_song_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content_type', models.ForeignKey(blank=True, default=1, help_text='Select the ContentType corresponding to this condition.', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='celebration',
        ),
        migrations.RemoveField(
            model_name='song',
            name='celebration_types',
        ),
        migrations.RemoveField(
            model_name='song',
            name='liturgical_season',
        ),
        migrations.RemoveField(
            model_name='song',
            name='occasions',
        ),
        migrations.RenameModel(
            old_name='Occasion',
            new_name='MassPart',
        ),
        migrations.CreateModel(
            name='LiturgicalSubSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('priority', models.IntegerField(choices=[(0, 'default'), (1, 'preferred'), (2, 'strongly preferred'), (3, 'mandatory')], default=0)),
                ('exclusive', models.BooleanField(default=False, help_text='if a song with exclusive=True is selected, no other song is allowed in that mass part.')),
                ('can_be_main', models.BooleanField(default=True)),
                ('condition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.conditiontype')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['liturgicalseason', 'liturgicalsubseason', 'celebration', 'celebrationtype']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('mass_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.masspart')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
        ),
    ]
