# Generated by Django 5.1.3 on 2025-03-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_conditiontype_remove_song_celebration_and_more_squashed_0006_liturgicalsubseason_alter_songrule_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='has_communion_verse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='has_recessional_verse',
            field=models.BooleanField(default=False),
        ),
    ]
